# Generated by Django 5.1.1 on 2024-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeeid', models.CharField(max_length=100)),
                ('Employeepname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
