# Generated by Django 5.1.1 on 2024-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employeeid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employeepname',
            new_name='employee_name',
        ),
    ]
